export const vitaminFoods = [
  {
    name: "sweetPotato",
    description: "Sweet Potatoes",
    isVegan: true,
    vitamins: {
      a: 400,
      c: 20,
      b6: 17.5,
      b7: 10,
      e: 4,
    },
  },
  {
    name: "carrot",
    description: "Carrots",
    isVegan: true,
    vitamins: {
      a: 200,
      k: 15,
      b6: 3,
      b7: 2,
    },
  },
  {
    name: "leafy",
    description: "Leafy Greens (Spinach, Kale)",
    isVegan: true,
    vitamins: {
      a: 100,
      c: 100,
      k: 550,
      b2: 15,
      b6: 7,
      b7: 6,
      e: 8,
    },
  },
  {
    name: "grains",
    description: "Whole Grains (Brown Rice, Whole Wheat, Oats)",
    isVegan: true,
    vitamins: {
      b1: 15,
      b2: 5,
      b3: 15,
      b5: 8,
      b6: 8,
      b7: 7,
    },
  },
  {
    name: "cereal",
    description: "Cereal",
    isVegan: true,
    vitamins: {
      a: 20,
      b1: 20,
      b2: 20,
      b3: 20,
      b5: 20,
      b6: 20,
      b9: 20,
      d: 25,
      e: 20,
    },
  },
  {
    name: "legume",
    description: "Legumes (Beans, Lentils, Chickpeas)",
    isVegan: true,
    vitamins: {
      b1: 20,
      b2: 5,
      b3: 10,
      b5: 10,
      b6: 10,
      b7: 5,
      b9: 23,
    },
  },
  {
    name: "nuts",
    description: "Nuts (Almonds, Walnuts, Peanuts)",
    isVegan: true,
    vitamins: {
      b1: 10,
      b2: 5,
      b3: 5,
      b6: 5,
      b7: 15,
      b9: 10,
      e: 35,
    },
  },
  {
    name: "seeds",
    description: "Seeds (Sunflower Seeds, Pumpkin Seeds)",
    isVegan: true,
    vitamins: {
      b1: 25,
      b5: 20,
      b6: 10,
      b7: 10,
      b9: 18,
      e: 40,
      k: 10,
    },
  },
  {
    name: "avocado",
    description: "Avocado",
    isVegan: true,
    vitamins: {
      e: 10,
      k: 10,
      c: 10,
      b1: 6,
      b5: 30,
      b6: 10,
      b7: 5,
      b9: 5,
    },
  },
  {
    name: "mushrooms",
    description: "Mushrooms",
    isVegan: true,
    vitamins: {
      b2: 10,
      b3: 10,
      d: 10,
    },
  },
  {
    name: "banana",
    description: "Bananas",
    isVegan: true,
    vitamins: {
      b6: 10,
      c: 10,
      b9: 5,
    },
  },
  {
    name: "citrus",
    description: "Citrus Fruits (Oranges, Grapefruits)",
    isVegan: true,
    vitamins: {
      c: 25,
      b1: 18,
      b9: 10,
    },
  },
  {
    name: "pepper",
    description: "Bell Peppers",
    isVegan: true,
    vitamins: {
      c: 150,
      a: 10,
      e: 10,
      b6: 10,
    },
  },
  {
    name: "berries",
    description: "Berries (Blueberries, Raspberries)",
    isVegan: true,
    vitamins: {
      c: 25,
      k: 10,
      e: 10,
      b6: 5,
    },
  },
  {
    name: "tomato",
    description: "Tomatoes",
    isVegan: true,
    vitamins: {
      c: 20,
      a: 10,
      k: 10,
      e: 10,
    },
  },
  {
    name: "strawberry",
    description: "Strawberries",
    isVegan: true,
    vitamins: {
      c: 150,
      b6: 5,
      k: 5,
    },
  },
  {
    name: "cruci",
    description: "Cruciferous Vegetables (Broccoli, Brussels Sprouts)",
    isVegan: true,
    vitamins: {
      c: 130,
      k: 120,
      e: 10,
      b6: 5,
      b7: 5,
    },
  },
  {
    name: "grapes",
    description: "Grapes",
    isVegan: true,
    vitamins: {
      c: 5,
      k: 5,
      e: 5,
      b6: 5,
    },
  },
  {
    name: "kiwi",
    description: "Kiwifruit",
    isVegan: true,
    vitamins: {
      c: 240,
      e: 10,
      k: 10,
    },
  },
  {
    name: "watermelon",
    description: "Watermelon",
    isVegan: true,
    vitamins: {
      b1: 5,
      b3: 3,
      b5: 7,
      b6: 15,
      b9: 4,
      a: 17,
      c: 32,
    },
  },

  {
    name: "asparagus",
    description: "Asparagus",
    isVegan: true,
    vitamins: {
      b2: 5,
      b6: 5,
      b9: 60,
      k: 60,
      c: 20,
      a: 20,
    },
  },
  {
    name: "garlic",
    description: "Garlic",
    isVegan: true,
    vitamins: {
      b1: 5,
      b6: 5,
      c: 5,
    },
  },
  {
    name: "corn",
    description: "Sweet Corn",
    isVegan: true,
    vitamins: {
      b1: 10,
      b5: 10,
      b3: 15,
      b6: 10,
    },
  },
  {
    name: "pineapple",
    description: "Pineapple",
    isVegan: true,
    vitamins: {
      b1: 10,
      c: 130,
      b5: 10,
      b6: 10,
    },
  },
  {
    name: "cherries",
    description: "Cherries",
    isVegan: true,
    vitamins: {
      a: 10,
      c: 10,
      k: 10,
    },
  },
  {
    name: "quinoa",
    description: "Quinoa",
    isVegan: true,
    vitamins: {
      b1: 15,
      b2: 10,
      b5: 8,
      b6: 25,
      b7: 4,
      b9: 5,
      e: 10,
    },
  },
  {
    name: "seaweed",
    description: "Seaweed",
    isVegan: true,
    vitamins: {
      b12: 50,
      a: 5,
      b9: 5,
      c: 25,
      e: 5,
      k: 40,
    },
  },
  {
    name: "plantMilk",
    description: "Fortified Plant Milks (Almond, Soy, Rice)",
    isVegan: true,
    vitamins: {
      b1: 10,
      b2: 25,
      b5: 7,
      b7: 3,
      b12: 25,
      d: 25,
      a: 10,
    },
  },
  {
    name: "yeast",
    description: "Nutritional Yeast",
    isVegan: true,
    vitamins: {
      b1: 5,
      b5: 7,
      b7: 12,
      b12: 40,
    },
  },
  {
    name: "chia",
    description: "Chia Seeds",
    isVegan: true,
    vitamins: {
      b1: 6,
      b2: 5,
      e: 10,
    },
  },
  {
    name: "flax",
    description: "Flaxseeds",
    isVegan: true,
    vitamins: {
      b1: 6,
      e: 10,
      b6: 6,
    },
  },
  {
    name: "tofu",
    description: "Tofu",
    isVegan: true,
    vitamins: {
      b1: 12,
      b2: 7,
      b3: 7,
      b5: 7,
      b6: 7,
      b7: 7,
      b9: 7,
      d: 15,
    },
  },
  {
    name: "chicken",
    description: "Lean Meat (Beef, Pork, Poultry)",
    isVegan: false,
    vitamins: {
      a: 2,
      b1: 10,
      b2: 15,
      b3: 55,
      b5: 10,
      b6: 35,
      b9: 5,
      b12: 15,
      d: 2,
      e: 7,
      k: 5,
    },
  },
  {
    name: "dairy",
    description: "Dairy Products (Milk, Yogurt, Cheese)",
    isVegan: false,
    vitamins: {
      b2: 15,
      b5: 10,
      b12: 15,
      d: 15,
      a: 10,
    },
  },
  {
    name: "egg",
    description: "Eggs",
    isVegan: false,
    vitamins: {
      b1: 10,
      b2: 15,
      b5: 30,
      b7: 20,
      b12: 15,
      d: 15,
      a: 10,
      e: 5,
    },
  },
  {
    name: "fish",
    description: "Fatty Fish (Tuna, Salmon, Mackerel)",
    isVegan: false,
    vitamins: {
      b2: 25,
      b3: 60,
      b5: 15,
      b6: 55,
      b7: 15,
      b12: 50,
      d: 300,
      a: 50,
      e: 8,
    },
  },
  {
    name: "liver",
    description: "Liver",
    isVegan: false,
    vitamins: {
      a: 600,
      b1: 25,
      b2: 200,
      b3: 80,
      b5: 60,
      b6: 70,
      b7: 8,
      b9: 90,
      b12: 1500,
    },
  },
  {
    name: "shellfish",
    description: "Shellfish",
    isVegan: false,
    vitamins: {
      b3: 25,
      b6: 25,
      b12: 200,
      a: 7,
      c: 15,
      d: 15,
      e: 7,
    },
  },
];
