export const polishText = {
  navigation: {
    signIn: "Zaloguj się",
    signUp: "Zarejestruj się",
    signOut: "Wyloguj się",
  },
  footer: {
    contact: "Kontakt",
    about: "O nas",
    privacyPolicy: "Polityka prywatności",
  },
  home: {
    header: "Liczymy Dane, Wzmaciamy Zdrowie!",
    subheader: `Odkryj swoje spersonalizowane dzienne zapotrzebowanie na witaminy i analizuj swoją dietę, aby osiągnąć optymalne zdrowie. I jako wisienka na torcie, delektuj się propozycjami wyjątkowych przepisów!`,
    button: "Do dzieła!",
    scroll: "Przewiń w dół, aby zobaczyć więcej",
    calculatorDescription: `Odkryj swoje dzienne zapotrzebowanie na witaminy w kilka sekund! Wybierz witaminę, podaj swój wiek i płeć, a otrzymasz spersonalizowane zalecenia. Optymalizuj swoje zdrowie bez wysiłku!`,
    deficitDescription: `Wybierz swoje posiłki, a nasz inteligentny algorytm wskaże braki w witaminach. Dostaniesz spersonalizowane wskazówki do optymalizacji diety i poprawy samopoczucia. Odkryj swoje niedobory i żyj lepiej!`,
    moreFeatures: "Więcej funkcji już wkrótce!",
  },
  calculator: {
    didYouKnow: "Czy wiedziałeś, że",
    vitaminFunFacts: [
      "witamina A jest Cudem Przyciągającym Wzrok: wspiera oczy i zdrowie skóry, działając jak reflektor natury dla twoich oczu.",
      "witamina B1 (tiamina) to Energiczna Komórka: zamienia Twoje jedzenie w czystą energię, zapewniając płynną pracę elektrowni w Twoim organizmie.",
      "witamina B2 (ryboflawina) to Sojusznik Pięknej Skóry: nie tylko dba o zdrową cerę, ale także wspiera produkcję energii w Twoim ciele.",
      "witamina B3 (niacyna) to Mistrz Krążenia: działa na korzyść Twojego serca i poziomu cholesterolu, pomagając utrzymać zdrowie serca.",
      "witamina B5 (kwas pantotenowy) to Dynamo Energetyczne: przemienia jedzenie w energię i pielęgnuje zdrowie skóry.",
      "witamina B6 to Modulator Nastroju: wspomaga działanie mózgu, pomagając utrzymać równowagę emocjonalną i zdrowy sen.",
      "witamina B7 (biotyna) to Sekret Piękna: wspiera zdrowie włosów, skóry i paznokci, sprawiając, że wyglądasz oszałamiająco",
      "witamina B9 (kwas foliowy) to Architekt DNA: jest niezbędna do wzrostu komórek i kluczowa w okresie ciąży.",
      "witamina B12 to Nawigator Nerwowy: dba o prawidłowe funkcjonowanie układu nerwowego i produkcję krwinek czerwonych.",
      "witamina C to Bohater Oporności: wzmacnia Twój układ odpornościowy i wspomaga produkcję kolagenu, chroniąc Twój organizm.",
      "witamina D to Najlepszy Przyjaciel Kości: znana jako witamina słoneczna, wspiera zdrowie kości, poprawia nastrój i wzmacnia funkcjonowanie układu odpornościowego.",
      "witamina E to Pogromca Wolnych Rodników: broni Twoje komórki przed uszkodzeniami i pielęgnuje zdrowie skóry.",
      "witamina K to Ekspert Krzepnięcia Krwi: pomaga w procesie krzepnięcia krwi i wspiera zdrowe kości.",
    ],
    and: "i",
    recommendedIntake: "Zalecane dzienne spożycie witaminy",
    amountsTo: "wynosi",
    recommendedSources: "Świetne źródła tej witaminy to",
    vitaminSources: {
      c: ["pomarańcze", "truskawki", "papryka"],
      b1: ["nasiona słonecznika", "czarna fasola", "orzechy brazylijskie"],
      b2: ["jajka", "szpinak", "mleko"],
      b3: ["kurczak", "indyk", "łosoś"],
      b5: ["awokado", "jogurt", "kalafior"],
      b6: ["banany", "kurczak", "ryba"],
      b7: ["orzechy włoskie", "jajka", "słonecznik"],
      b9: ["szpinak", "wątróbka", "soczewica"],
      b12: ["mleko", "jogurt", "sardynki"],
      a: ["bataty", "marchewki", "jarmuż"],
      d: ["łosoś", "twaróg", "grzyby"],
      e: ["orzechy migdałowe", "szpinak", "olej słonecznikowy"],
      k: ["szpinak", "kapusta", "pomidory"],
    },
    header: "Witaminkomierz",
    choose: "Wybierz swoją witaminę",
    age: "Wiek",
    male: "Mężczyzna",
    female: "Kobieta",
    sex: "Płeć",
    button: "Oblicz",
  },
  info: {
    header: "Zrozumieć Witaminy",
    vitamin: "Witamina",
    vitaminInfo: {
      c: "Odpowiada za ochronę antyoksydacyjną i wspieranie układu odpornościowego. Występuje w owocach cytrusowych i papryce. Pełni kluczową rolę w produkcji kolagenu dla zdrowia skóry.",
      b1: "Niezbędna do metabolizmu energetycznego i prawidłowego funkcjonowania nerwów. Typowe źródła to pełne ziarno i wieprzowina. Niedobór może prowadzić do beri-beri, wpływając na układ nerwowy.",
      b2: "Odpowiada za wzrost komórek i produkcję energii. Występuje w produktach mlecznych i jajkach. Pomaga również w produkcji czerwonych krwinek i wspomaga zdrowie oczu.",
      b3: "Wspiera trawienie i promuje zdrową skórę. Znajduje się w mięsie i orzeszkach ziemnych, pomaga również obniżyć poziom złego cholesterolu.",
      b5: "Bierze udział w produkcji hormonów i metabolizmie. Źródła to między innymi kurczak i awokado. Pełni istotną rolę w regulacji reakcji organizmu na stres oraz w funkcji nadnerczy",
      b6: "Niezbędna dla rozwoju i funkcjonowania mózgu. Występuje w rybach i bananach, pomaga także organizmowi przekształcać jedzenie w użyteczną energię.",
      b7: "Znana z wspierania wytrzymałości włosów, skóry i paznokci. Typowe źródła to jajka i orzechy. Często jest dodawana do produktów kosmetycznych ze względu na swoje korzyści.",
      b9: "Ważna dla syntezy DNA i podziału komórek. Znajduje się w zielonych warzywach liściastych, jest szczególnie w czasie ciąży w celu zapobiegania wadom cewy nerwowej.",
      b12: "Niezbędna do funkcji nerwów i tworzenia czerwonych krwinek. Głównie występuje w produktach zwierzęcych, co czyni ją kluczowym suplementem dla wegetarian.",
      a: "Skupia się przede wszystkim na wsparciu widzenia i układu odpornościowego. Znajduje się w marchwiach i słodkich ziemniakach, jest niezbędna dla zdrowia oczu, w tym utrzymania zdolności do widzenia w warunkach o ograniczonym oświetleniu.",
      d: "Niezbędna dla zdrowia kości i wchłaniania wapnia. Uzyskiwana z ryb lub ekspozycji na światło słoneczne, pomaga także w walce z chorobami, takimi jak osteoporoza.",
      e: "Działa jako przeciwutleniacz i wspiera zdrowie skóry. Typowe źródła to migdały i szpinak. Chroni błony komórkowe przed uszkodzeniami.",
      k: "Znajduje się w produktach takich jak jarmuż i szpinak, odgrywa kluczową rolę w procesie krzepnięcia krwi oraz wspiera zdrowie kości, co przyczynia się do zapobiegania osteoporozie.",
    },
  },
  deficit: {
    unauthorised: "Musisz być zalogowany, aby korzystać z tej funkcji",
    header: "Witaminowy Radar",
    subheader: "Zaznacz jedzenie, które spożywałeś w ciągu ostatnich dni",
    opinionGood:
      "Twoje odpowiedzi sugerują, że utrzymujesz zdrowy poziom witamin! Jednak dla pewności warto skonsultować się z lekarzem i rozważyć badanie krwi.",
    opinionBadStart:
      "Na podstawie Twojego wyboru, istnieje ryzyko, że masz niedobór witamin:",
    opinionBadEnd:
      "Jednakże, zalecamy skonsultowanie się z lekarzem i wykonanie badania krwi.",
    foodDescriptions: {
      sweetPotato: "Bataty",
      carrot: "Marchewki",
      leafy: "Zielone warzywa liściaste (szpinak, jarmuż, rukola)",
      grains: "Pełne ziarno (brązowy ryż, ciemne pieczywo, płatki owsiane)",
      cereal: "Płatki śniadaniowe",
      legume: "Rośliny strączkowe (fasola, soczewica, ciecierzyca)",
      nuts: "Orzechy (migdały, orzechy włoskie, orzeszki ziemne)",
      seeds: "Nasiona (nasiona słonecznika, nasiona dyni)",
      avocado: "Awokado",
      mushrooms: "Grzyby",
      banana: "Banany",
      citrus: "Owoce cytrusowe (pomarańcze, grejpfruty, mandarynki)",
      pepper: "Papryka",
      berries: "Owoce jagodowe (borówki, maliny, żurawina)",
      tomato: "Pomidory",
      strawberry: "Truskawki",
      cruci: "Warzywa krzyżowe (brokuły, kalafior, brukselka)",
      grapes: "Winogrona",
      kiwi: "Kiwi",
      watermelon: "Arbuz",
      asparagus: "Szparagi",
      garlic: "Czosnek",
      corn: "Kukurydza",
      pineapple: "Ananas",
      cherries: "Wiśnie",
      quinoa: "Komosa ryżowa",
      seaweed: "Wodorosty",
      plantMilk: "Mleko roślinne (migdałowe, sojowe, ryżowe)",
      yeast: "Drożdże odżywcze",
      chia: "Nasiona chia",
      flax: "Siemię lniane",
      tofu: "Tofu",
      chicken: "Chude mięso (schab, pierś z kurczaka)",
      dairy: "Produkty mleczne (jogurt, ser, masło)",
      egg: "Jajka",
      fish: "Tłuste ryby (tuńczyk, łosoś, makrela)",
      liver: "Wątróbka",
      shellfish: "Skorupiaki",
    },
    check: "Odkryj, czego Ci brakuje!",
  },
  signUp: {
    header: "Rejestracja",
    subheader: "Utwórz darmowe konto za pomocą swojego adresu e-mail",
    placeholderName: "Imię",
    placeholderEmail: "E-mail",
    placeholderPassword: "Hasło",
    placeholderAge: "Wiek",
    button: "Zarejestruj się",
    haveAnAccount: "Masz już konto?",
    logIn: "Zaloguj się",
    accountCreated: "Twoje konto zostało pomyślnie utworzone!",
    verifyEmail: "Potwierdź swój adres e-mail.",
    errorEmptyName: "Imię nie może być puste",
    errorEmptyEmail: "E-mail nie może być pusty",
    errorEmptyPassword: "Hasło nie może być puste",
    errorEmptyAge: "Wiek nie może być pusty",
    errorInvalidName:
      "Imię powinno zawierać tylko litery i spacje, maksymalnie 50 znaków",
    errorInvalidEmail: "E-mail jest nieprawidłowy",
    errorInvalidPassword:
      "Hasło musi mieć co najmniej 8 znaków, w tym 1 wielką literę i 1 znak specjalny",
    errorInvalidAge: "Wiek musi być w przedziale od 0 do 90 lat",
    errorUserExists: "Konto z tym adresem e-mail już istnieje",
  },
  signIn: {
    header: "Logowanie",
    subheader: "Zaloguj się na swoje konto",
    placeholderEmail: "E-mail",
    placeholderPassword: "Hasło",
    button: "Zaloguj się",
    noAccount: "Nie masz konta?",
    signUp: "Zarejestruj się",
    errorEmptyEmail: "E-mail nie może być pusty",
    errorEmptyPassword: "Hasło nie może być puste",
    errorInvalidEmail: "E-mail jest nieprawidłowy",
    errorIncorrectPassword: "Nieprawidłowe hasło",
    errorNotVerified: "Twoje konto nie zostało zweryfikowane",
    errorUserNotFound: "Użytkownik nie został znaleziony",
  },
  profile: {
    header: "Twój profil",
    dailyIntake: "Zalecana dzienna dawka witamin",
    vitamin: "Witamina",
    name: "Imię",
    email: "E-mail",
    age: "Wiek",
    sex: "Płeć",
    placeholderName: "Imię",
    placeholderEmail: "E-mail",
    placeholderAge: "Nie ustawiono",
    male: "Mężczyzna",
    female: "Kobieta",
    saved: "Zmiany zostały pomyślnie zapisane!",
    button: "Zapisz zmiany",
    errorEmptyName:
      "Imię nie może być puste i może zawierać tylko litery oraz spacje",
    errorLongName: "Imię nie może być dłuższe niż 50 znaków",
    errorInvalidAge: "Wiek musi być w przedziale od 0 do 90 lat",
  },
  emailVerification: {
    verified: "E-mail został pomyślnie zweryfikowany!",
    expired: "Twój link weryfikacyjny wygasł",
    signAgain: "Zarejestruj się ponownie.",
  },
  error: {
    header: "Ta strona nie istnieje :(",
    subheader: "Przejdź na stronę główną",
  },
  contact: {
    header: "Skontaktuj się z nami",
    subheader: "Zapraszamy do wysłania wiadomości",
    placeholderEmail: "E-mail",
    placeholderSubject: "Temat",
    placeholderMessage: "Wpisz tutaj swoją wiadomość",
    button: "Wyślij",
    errorEmptyEmail: "E-mail nie może być pusty",
    errorEmptySubject: "Temat nie może być pusty",
    errorEmptyMessage: "Wiadomość nie może być pusta",
    errorInvalidEmail: "E-mail jest nieprawidłowy",
  },
  about: {
    header: "O VitQnt",
    welcome: "Witaj w VitQnt,",
    subheader: `Twoim głównym miejscu przeznaczenia dla spersonalizowanych porad dotyczących zdrowia i odżywiania. Założony przez Kubę Nowoszyńskiego,
        VitQnt powstał z pilnej potrzeby uproszczenia skomplikowanego świata
        witamin. Zdajemy sobie sprawę, że utrzymanie zrównoważonej
        diety może być przytłaczające, dlatego jesteśmy tutaj, aby zaoferować ci
        spersonalizowane podejście oparte na danych do Twojego zdrowia.`,
    heading1: "Nasz cel",
    paragraph1: `Głównym celem VitQnt jest umożliwienie Tobie dostosowanych rekomendacji
        dotyczących codziennego. Uwzględniamy
        indywidualne czynniki, takie jak wiek i płeć, abyś otrzymał
        najdokładniejsze i najkorzystniejsze rady. Z VitQnt od zdrowszego stylu życia dzieli Cię zaledwie kilka kliknięć.`,
    heading2: `Funkcje, które pokochasz`,
    bolded1: "Codzienne zalecenia dotyczące witamin:",
    list1: `koniec ze zgadywaniem. Uzyskaj dokładne wartości dziennego spożycia oparte na Twoich osobistych parametrach.`,
    bolded2: `Panel informacyjny:`,
    list2: `ciekawi Cię, za co odpowiedzialna jest każda witamina? Odkrywaj szczegółowe informacje.`,
    bolded3: `Analiza diety:`,
    list3: `rejestruj swoje codzienne posiłki i pozwól naszym zaawansowanym algorytmom wskazać obszary, w których Twoja dieta może być niewystarczająca.`,
    bolded4: `(Wkrótce) Zalecenia dotyczące przepisów:`,
    list4: `zapełnianie luki w witaminach nigdy nie było łatwiejsze! Otrzymuj wybrane propozycje przepisów zaprojektowane tak, aby zaspokoić wszelkie braki, jakie możesz mieć.`,
    footer: `Odkryj moc spersonalizowanego żywienia z VitQnt i podążaj ku zdrowszemu sobie już dziś!`,
  },
  privacyPolicy: {
    header: "Polityka prywatności VitQnt",
    subheader: "Ostatnia aktualizacja: 6 września 2023",
    heading1: "Wprowadzenie",
    paragraph1: ` Witaj w VitQnt! Twoja prywatność jest dla nas najwyższym priorytetem. Niniejsza
          polityka prywatności ma na celu poinformowanie Cię o rodzajach 
          informacji, które zbieramy, jak je wykorzystujemy oraz jakie środki
          podejmujemy, aby je chronić. Korzystając z naszych usług, zgadzasz się 
          na warunki opisane polityce prywatności.`,
    heading2: "Ciasteczka (Cookies)",
    paragraph2: `W celu poprawy komfortu korzystania z naszego serwisu, używamy ciasteczek, aby utrzymać Cię zalogowanym
          podczas korzystania z naszej platformy. Ciasteczka to małe pliki danych
          przechowywane w Twojej przeglądarce, które zapamiętują Twoje dane logowania, dzięki czemu nie musisz
          wprowadzać ich za każdym razem, gdy odwiedzasz naszą stronę.`,
    heading3: "Pamięć lokalna (Local Storage)",
    paragraph3: `Aby zapewnić bardziej spersonalizowane doświadczenie podczas przeglądania, przechowujemy
          Twoje wybrane ustawienia językowe w pamięci lokalnej. Umożliwia nam to
          prezentowanie naszych treści w języku, w którym czujesz się najbardziej komfortowo.`,
    heading4: "Jak chronimy Twoje informacje",
    paragraph4: `Wdrażamy różnorodne środki bezpieczeństwa, aby chronić Twoje dane osobowe.
          Dostęp do Twoich danych użytkownika jest ograniczony tylko dla upoważnionych
          pracowników i przechowywany w bezpiecznych bazach danych.`,
    heading5: "Zmiany w polityce prywatności",
    paragraph5: `Zastrzegamy sobie prawo do aktualizacji lub modyfikacji polityki prywatności w
          dowolnym momencie. Zaktualizowana wersja zostanie opublikowana na tej stronie i będzie
          obowiązywać natychmiast po jej opublikowaniu.`,
    heading6: "Skontaktuj się z nami",
    paragraph6: `Jeśli masz jakiekolwiek pytania dotyczące polityki prywatności, prosimy o kontakt pod adresem`,
  },
};
