export const polishText = {
  navigation: {
    signIn: "Zaloguj się",
    signUp: "Zarejestruj się",
    signOut: "Wyloguj się",
  },
  footer: {
    contact: "Kontakt",
    about: "O nas",
    privacyPolicy: "Polityka prywatności",
  },
  home: {
    header: "Analiza liczb, promowanie zdrowia!",
    subheader: `Odkryj swoje spersonalizowane dzienne zapotrzebowanie na składniki odżywcze, zgłęb wiedzę na temat witamin i analizuj swoją dietę dla optymalnego zdrowia. Plus, ciesz się propozycjami przepisów!`,
    scroll: "Przewiń w dół, aby zobaczyć więcej",
    calculatorDescription: `Odkryj swoje dzienne zapotrzebowanie na witaminy w kilka sekund! Wybierz witaminę, podaj swój wiek i płeć, a otrzymasz spersonalizowane zalecenia. Optymalizuj swoje zdrowie bez wysiłku!`,
    deficitDescription: `Zaloguj swoje ostatnie posiłki i pozwól naszemu inteligentnemu algorytmowi zidentyfikować potencjalne braki w witaminach. Od witaminy A do K, otrzymuj spersonalizowane wskazówki, aby optymalizować swoją dietę i samopoczucie. Odkryj, czego brakuje i rozkwitaj!`,
    moreFeatures: "Więcej funkcji wkrótce!",
  },
  calculator: {
    didYouKnow: "Czy wiedziałeś, że",
    vitaminFunFacts: [
      "witamina A jest cudem przyciągającym wzrok: wspiera wzrok i zdrowie skóry, działając jak reflektor natury dla twoich oczu.",
      "witamina B1 (Tiamina) to energiczna komórka: przekształca jedzenie w energię, zapewniając płynne działanie elektrowni twojego ciała.",
      "witamina B2 (Ryboflawina) to sojusznik skóry: pomaga utrzymać zdrową skórę i wspiera produkcję energii w organizmie.",
      "witamina B3 (Niacyna) to mistrz układu krążenia: pomaga w utrzymaniu zdrowych poziomów cholesterolu i wspiera zdrowie serca.",
      "witamina B5 (Kwas pantotenowy) to dynamo energetyczne: pomaga przekształcać jedzenie w energię i przyczynia się do zdrowia skóry.",
      "witamina B6 to modulator nastroju: wspiera funkcjonowanie mózgu i pomaga regulować nastrój i wzorce snu.",
      "witamina B7 (Biotyna) to wzmacniacz urody: promuje zdrowie włosów, skóry i paznokci, pomagając ci wyglądać jak najlepiej.",
      "witamina B9 (Kwas foliowy) to projektant DNA: jest niezbędna do podziału komórek i wspiera rozwój płodowy podczas ciąży.",
      "witamina B12 to nawigator nerwowy: wspomaga funkcjonowanie nerwów i pomaga w produkcji czerwonych krwinek.",
      "witamina C to bohater odporności: ten przeciwutleniacz wspiera układ odpornościowy i pomaga w produkcji kolagenu.",
      "witamina D to najlepszy przyjaciel kości: znana jako witamina słoneczna, wspiera zdrowie kości, nastrój i funkcjonowanie układu odpornościowego.",
      "witamina E to mściciel przeciwutleniacza: chroni komórki przed uszkodzeniami i wspiera zdrowie skóry.",
      "witamina K to mistrz krzepnięcia krwi: pomaga w krzepnięciu krwi i wspiera zdrowie kości.",
    ],
    and: "i",
    recommendedIntake: "Zalecane dzienne spożycie witaminy",
    amountsTo: "wynosi",
    recommendedSources: "Świetne źródła witaminy to",
    vitaminSources: {
      c: ["pomarańcze", "truskawki", "papryka"],
      b1: ["nasiona słonecznika", "czarne fasoli", "orzechy brazylijskie"],
      b2: ["jajka", "szpinak", "mleko"],
      b3: ["kurczak", "indyk", "łosoś"],
      b5: ["awokado", "jogurt", "kalafior"],
      b6: ["banany", "kurczak", "ryba"],
      b7: ["orzechy włoskie", "jajka", "słonecznik"],
      b9: ["szpinak", "kiełki", "soczewica"],
      b12: ["mleko", "jogurt", "sardynki"],
      d: ["łosoś", "twaróg", "grzyby"],
      e: ["orzechy migdałowe", "szpinak", "olej słonecznikowy"],
      k: ["szpinak", "kapusta", "pomidor"],
    },
    header: "Kalkulator Spożycia Witamin",
    choose: "Wybierz swoją witaminę",
    age: "Wiek",
    male: "Mężczyzna",
    female: "Kobieta",
    sex: "Płeć",
  },
  info: {
    header: "Rozumienie Witamin",
    vitamin: "Witamina",
    vitaminInfo: {
      c: "Odpowiada za ochronę antyoksydacyjną i wspieranie układu odpornościowego. Często występuje w owocach cytrusowych i papryce. Pełni kluczową rolę w produkcji kolagenu dla zdrowia skóry.",
      b1: "Niezbędna do metabolizmu energetycznego i prawidłowego funkcjonowania nerwów. Typowe źródła to ziarna pełne i wieprzowina. Niedobór może prowadzić do beri-beri, wpływając na układ nerwowy.",
      b2: "Odpowiada za wzrost komórek i produkcję energii. Często występuje w produktach mlecznych i jajkach. Pomaga również w produkcji czerwonych krwinek i zdrowiu oczu.",
      b3: "Pomaga w trawieniu i promuje zdrową skórę. Znajduje się w mięsie i orzeszkach ziemnych, pomaga również obniżyć poziom złego cholesterolu.",
      b5: "Bierze udział w produkcji hormonów i metabolizmie. Źródła to między innymi kurczak i awokado. Ważna dla stresu i funkcji nadnerczy.",
      b6: "Niezbędna dla rozwoju i funkcjonowania mózgu. Często występuje w rybach i bananach, pomaga także organizmowi przekształcać jedzenie w użyteczną energię.",
      b7: "Znana z wspierania włosów, skóry i paznokci. Typowe źródła to jajka i orzechy. Często jest dodawana do produktów kosmetycznych ze względu na te korzyści.",
      b9: "Ważna dla syntezy DNA i podziału komórek. Znajduje się w zielonych warzywach liściastych, jest szczególnie ważna podczas ciąży w celu zapobiegania wadom cewy nerwowej.",
      b12: "Niezbędna do funkcji nerwów i tworzenia czerwonych krwinek. Głównie występuje w produktach zwierzęcych, co czyni ją kluczowym suplementem dla wegetarian.",
      a: "Skupia się przede wszystkim na wsparciu widzenia i układu odpornościowego. Znajduje się w marchwiach i słodkich ziemniakach, jest niezbędna dla widzenia nocnego i zdrowia skóry.",
      d: "Niezbędna dla zdrowia kości i wchłaniania wapnia. Uzyskiwana z ryb lub ekspozycji na światło słoneczne, pomaga także w walce z chorobami, takimi jak osteoporoza.",
      e: "Działa jako przeciwutleniacz i wspiera zdrowie skóry. Typowe źródła to migdały i szpinak. Chroni błony komórkowe przed uszkodzeniami.",
      k: "Niezbędna do krzepnięcia krwi i zdrowia kości. Znajduje się w produktach takich jak jarmuż i szpinak, jest ważna dla gojenia się ran i zapobiegania osteoporozie.",
    },
  },
  deficit: {
    unauthorised: "Musisz być zalogowany, aby korzystać z tej funkcji",
    header: "Sprawdzanie Niedoboru Witamin",
    subheader: "Wybierz jedzenie, które jadłeś w ostatnich dniach",
    opinionGood:
      "Wygląda na to, że radzisz sobie dobrze z witaminami na podstawie Twoich odpowiedzi! Jednak zawsze warto skonsultować się z lekarzem i rozważyć badanie krwi dla pewności.",
    opinionBadStart:
      "Na podstawie Twojego wyboru możesz być narażony na niedobory witamin:",
    opinionBadEnd:
      "Sugerujemy jednak skontaktowanie się ze specjalistą i wykonanie badania krwi.",
    foodDescriptions: {
      sweetPotato: "Słodkie ziemniaki",
      carrot: "Marchewki",
      leafy: "Zielone warzywa liściaste (Szpinak, Jarmuż)",
      grains: "Całe ziarna (Brązowy ryż, Pełnoziarnista pszenica, Owsianka)",
      cereal: "Płatki śniadaniowe",
      legume: "Rośliny strączkowe (Fasola, Soczewica, Ciecierzyca)",
      nuts: "Orzechy (Migdały, Orzechy włoskie, Orzeszki ziemne)",
      seeds: "Nasiona (Nasiona słonecznika, Nasiona dyni)",
      avocado: "Awokado",
      mushrooms: "Grzyby",
      banana: "Banany",
      citrus: "Owoce cytrusowe (Pomarańcze, Grejpfruty)",
      pepper: "Papryki",
      berries: "Jagody (Borówki, Maliny)",
      tomato: "Pomidory",
      strawberry: "Truskawki",
      cruci: "Warzywa krzyżowe (Brokuły, Brukselki)",
      grapes: "Winogrona",
      kiwi: "Kiwi",
      watermelon: "Arbuz",
      asparagus: "Szparagi",
      garlic: "Czosnek",
      corn: "Kukurydza",
      pineapple: "Ananas",
      cherries: "Wiśnie",
      quinoa: "Komosa ryżowa",
      seaweed: "Wodorosty",
      plantMilk: "Wzmocnione mleka roślinne (Migdałowe, Sojowe, Ryżowe)",
      yeast: "Drożdże odżywcze",
      chia: "Nasiona chia",
      flax: "Siemię lniane",
      tofu: "Tofu",
      chicken: "Chude mięso (Wołowina, Wieprzowina, Drób)",
      dairy: "Produkty mleczne (Mleko, Jogurt, Ser)",
      egg: "Jajka",
      fish: "Tłuste ryby (Tuńczyk, Łosoś, Makrela)",
      liver: "Wątroba",
      shellfish: "Skorupiaki",
    },
    check: "Sprawdź swój niedobór",
  },
  signUp: {
    header: "Rejestracja",
    subheader: "Utwórz darmowe konto za pomocą swojego e-maila",
    placeholderName: "Pełne imię",
    placeholderEmail: "E-mail",
    placeholderPassword: "Hasło",
    placeholderAge: "Wiek",
    button: "Zarejestruj się",
    haveAnAccount: "Masz już konto?",
    logIn: "Zaloguj się",
    accountCreated: "Twoje konto zostało pomyślnie utworzone!",
    verifyEmail: "Proszę zweryfikować swój adres e-mail.",
    errorEmptyName: "Imię nie może być puste",
    errorEmptyEmail: "E-mail nie może być pusty",
    errorEmptyPassword: "Hasło nie może być puste",
    errorEmptyAge: "Wiek nie może być pusty",
    errorInvalidName: "Imię powinno być alfabetyczne, maksymalnie 50 znaków",
    errorInvalidEmail: "E-mail jest nieprawidłowy",
    errorInvalidPassword:
      "Hasło musi mieć co najmniej 8 znaków, w tym 1 wielką literę i 1 znak specjalny",
    errorInvalidAge: "Wiek musi być w przedziale od 0 do 90 lat",
  },
  signIn: {
    header: "Zaloguj się",
    subheader: "Zaloguj się na swoje konto",
    placeholderEmail: "E-mail",
    button: "Zaloguj się",
    noAccount: "Nie masz konta?",
    signUp: "Zarejestruj się",
    placeholderPassword: "Hasło",
    errorEmptyEmail: "E-mail nie może być pusty",
    errorEmptyPassword: "Hasło nie może być puste",
    errorInvalidEmail: "E-mail jest nieprawidłowy",
    errorIncorrectPassword: "Nieprawidłowe hasło",
    errorNotVerified: "Twoje konto nie zostało zweryfikowane",
    errorUserNotFound: "Użytkownik nie został znaleziony",
  },
  profile: {
    header: "Twój profil",
    dailyIntake: "Twoje dzienne spożycie witamin",
    vitamin: "Witamina",
    name: "Imię",
    email: "E-mail",
    age: "Wiek",
    sex: "Płeć",
    placeholderName: "Pełne imię",
    placeholderEmail: "E-mail",
    placeholderAge: "Nie ustawiono",
    male: "Mężczyzna",
    female: "Kobieta",
    saved: "Zmiany zostały pomyślnie zapisane!",
    button: "Zapisz zmiany",
    errorEmptyName:
      "Imię nie może być puste i musi zawierać tylko litery i spacje",
    errorLongName: "Imię nie może być dłuższe niż 50 znaków",
    errorInvalidAge: "Wiek musi być w przedziale od 0 do 90 lat",
  },
  emailVerification: {
    verified: "E-mail został pomyślnie zweryfikowany!",
    expired: "Twój link weryfikacyjny wygasł",
    signAgain: "Proszę zarejestruj się ponownie.",
  },
  error: {
    header: "Ta strona nie istnieje :(",
    subheader: "Przejdź na stronę główną",
  },
  contact: {
    header: "Skontaktuj się z nami",
    subheader: "Zapraszamy do wysłania nam wiadomości",
    placeholderEmail: "E-mail",
    placeholderSubject: "Temat",
    placeholderMessage: "Wpisz tutaj swoją wiadomość",
    button: "Wyślij",
    errorEmptyEmail: "E-mail nie może być pusty",
    errorEmptySubject: "Temat nie może być pusty",
    errorEmptyMessage: "Wiadomość nie może być pusta",
    errorInvalidEmail: "E-mail jest nieprawidłowy",
  },
  about: {
    header: "O VitQnt",
    welcome: "Witaj w VitQnt,",
    subheader: `twoim głównym miejscu przeznaczenia dla spersonalizowanych porad dotyczących zdrowia i odżywiania. Założony przez Kubę Nowoszyńskiego,
        VitQnt powstał z pilnej potrzeby uproszczenia skomplikowanego świata
        witamin i mikroskładników. Zdajemy sobie sprawę, że utrzymanie zrównoważonej
        diety może być przytłaczające, dlatego jesteśmy tutaj, aby zaoferować ci
        spersonalizowane podejście oparte na danych do Twojego zdrowia.`,
    heading1: "Nasz cel",
    paragraph1: `Głównym celem VitQnt jest umożliwienie Ci dostosowanych rekomendacji
        dotyczących codziennego spożycia witamin i mikroskładników. Uwzględniamy
        indywidualne czynniki, takie jak wiek, płeć i wagę, abyś otrzymał
        najdokładniejsze i najkorzystniejsze rady. Z VitQnt twoja droga do zdrowszego stylu życia
        jest zaledwie kilka kliknięć.`,
    heading2: `Funkcje, które pokochasz`,
    bolded1: "Codzienne zalecenia dotyczące witamin i mikroskładników:",
    list1: `koniec z zgadywaniem; uzyskaj dokładne wartości dziennego spożycia oparte na Twoich osobistych parametrach.`,
    bolded2: `Panel informacyjny o składnikach odżywczych:`,
    list2: `ciekawi cię, co robi każdy składnik odżywczy? Odkrywaj szczegółowe informacje.`,
    bolded3: `Analiza diety:`,
    list3: `rejestruj swoje codzienne posiłki i pozwól naszym zaawansowanym algorytmom wskazać obszary, w których twoja dieta może być niewystarczająca.`,
    bolded4: `(Wkrótce) Zalecenia dotyczące przepisów:`,
    list4: `zapełnianie luki w składnikach odżywczych nigdy nie było łatwiejsze! Otrzymuj wybrane propozycje przepisów zaprojektowane tak, aby zaspokoić wszelkie braki, jakie możesz mieć. Odkryj moc spersonalizowanego żywienia z VitQnt i podążaj ku zdrowszej sobie już dziś!`,
    footer: `Odkryj moc spersonalizowanego żywienia z VitQnt i podążaj ku zdrowszej sobie już dziś!`,
  },
  privacyPolicy: {
    header: "Polityka prywatności VitQnt",
    subheader: "Ostatnia aktualizacja: 6 września 2023",
    heading1: "Wprowadzenie",
    paragraph1: ` Witaj w VitQnt! Twoja prywatność ma dla nas najwyższy priorytet. Niniejsza
          Polityka Prywatności ma na celu poinformowanie Cię o rodzajach 
          informacji, które zbieramy, jak je wykorzystujemy oraz jakie środki
          podejmujemy, aby je chronić. Korzystając z naszej usługi, zgadzasz się 
          na warunki opisane w tej Polityce Prywatności.`,
    heading2: "Ciasteczka (Cookies)",
    paragraph2: `W celu poprawy komfortu korzystania z naszego serwisu, używamy ciasteczek, aby utrzymać Cię zalogowanym
          podczas przeglądania naszej platformy. Ciasteczka to małe pliki danych
          przechowywane w Twojej przeglądarce, które zapamiętują Twoje dane logowania, dzięki czemu nie musisz
          wprowadzać ich za każdym razem, gdy odwiedzasz naszą stronę.`,
    heading3: "Lokalna pamięć (Local Storage)",
    paragraph3: `Aby zapewnić bardziej spersonalizowane doświadczenie podczas przeglądania, przechowujemy
          Twoje wybrane ustawienia językowe w lokalnej pamięci. Umożliwia nam to
          prezentowanie naszych treści w języku, w którym czujesz się najbardziej komfortowo.`,
    heading4: "Jak chronimy Twoje informacje",
    paragraph4: `Wdrażamy różnorodne środki bezpieczeństwa, aby chronić Twoje dane osobowe.
          Dostęp do Twoich danych użytkownika jest ograniczony tylko dla upoważnionych
          pracowników i przechowywany w bezpiecznych bazach danych.`,
    heading5: "Zmiany w tej Polityce Prywatności",
    paragraph5: `Zastrzegamy sobie prawo do aktualizacji lub modyfikacji tej Polityki Prywatności w
          dowolnym momencie. Zaktualizowana wersja zostanie opublikowana na tej stronie i będzie
          obowiązywać natychmiast po jej opublikowaniu.`,
    heading6: "Skontaktuj się z nami",
    paragraph6: `Jeśli masz jakiekolwiek pytania dotyczące tej Polityki Prywatności, prosimy o kontakt pod adresem`,
  },
};
